# Gowin EDA command line build:  gw_sh build.tcl [psram]
#   gw_sh build.tcl          BSRAM bring-up build, 8 colours (no IP needed)
#   gw_sh build.tcl psram    PSRAM build, full RGB565 - needs the Gowin PSRAM IP in
#                            ip/psram/ (see README, "PSRAM build")
set psram [expr {[llength $argv] > 0 && [lindex $argv 0] eq "psram"}]

set_device GW1NR-LV9QN88PC6/I5 -name GW1NR-9C
foreach f {lcd_timing test_pattern pll_pix spi_slave dbi_decoder framestore_bsram lcd_scanout small_lcd_bridge top} {
	add_file rtl/$f.v
}
if {$psram} {
	foreach f {async_fifo psram_ctrl pll_mem framestore_psram top_psram} { add_file rtl/$f.v }
	# IP generated by Gowin EDA (IP Core Generator -> PSRAM Memory Interface HS, burst length 16)
	foreach f [glob -nocomplain ip/psram/*.v ip/psram/*/*.v ip/psram/*.ipc ip/psram/*/*.ipc] { add_file $f }
	set_option -top_module top_psram
	set_option -output_base_name tangnano9k_lcd_psram
} else {
	add_file rtl/top_bsram.v
	set_option -top_module top_bsram
	set_option -output_base_name tangnano9k_lcd
}
add_file constraints/tangnano9k_lcd.cst
add_file constraints/tangnano9k.sdc
set_option -verilog_std v2001
set_option -use_sspi_as_gpio 1
set_option -use_mspi_as_gpio 1
set_option -use_done_as_gpio 1
set_option -use_ready_as_gpio 1
set_option -use_cpu_as_gpio 1
run all
