# SPDX-License-Identifier: GPL-2.0-only
# Armbian's AM625 vendor kernel is built with GCC 14 and uses compiler flags
# that GCC 13 does not understand. This override is loaded after TI's dkms.conf.
MAKE[0]="make KERNEL_CC=${KERNEL_CC:-gcc-14} KERNELDIR=${kernel_source_dir} BUILD=release PVR_BUILD_DIR=am62_linux WINDOW_SYSTEM=wayland"
