# SPDX-License-Identifier: GPL-2.0-only
# Load ASoC bits needed for GamePup MAX98357 on McASP2.
# Order: CPU DAI, codec DAI, then the card that binds them.
snd-soc-davinci-mcasp
snd-soc-max98357a
snd-soc-simple-card
